[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production]
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  command = "npm run lint && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
